import React, { useState, useEffect, useRef, useCallback } from 'react';

interface SummarySectionProps {
  articleNumber: string;
  articleTitle: string;
  articleContent: string;
  initialSummary?: string;
}

// Memòria global per guardar els resums generats per article
const summariesCache = new Map<string, string>();

const SummarySection: React.FC<SummarySectionProps> = ({
  articleNumber,
  articleTitle,
  articleContent,
  initialSummary,
}) => {
  // Funció per detectar si un resum és vàlid (no és només un fragment truncat)
  const isValidSummary = (summaryText: string | null | undefined): boolean => {
    if (!summaryText) return false;
    // Si el resum acaba amb "..." o és molt curt, probablement és un fragment truncat
    if (summaryText.endsWith('...') || summaryText.length < 50) return false;
    // Si comença amb números i punts (com "1. Es consideren..."), probablement és un fragment
    if (/^\d+\.\s/.test(summaryText.trim())) return false;
    return true;
  };

  const [summary, setSummary] = useState<string | null>(isValidSummary(initialSummary) ? (initialSummary || null) : null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isOpen, setIsOpen] = useState(false);
  const previousArticleNumber = useRef<string | null>(null);
  const hasAutoGenerated = useRef<boolean>(false);

  const generateSummary = useCallback(async (autoOpen: boolean = true) => {
    setLoading(true);
    setError(null);
    if (autoOpen) {
      setIsOpen(true);
    }

    try {
      const response = await fetch('/api/generate-summary', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          articleNumber,
          articleTitle,
          articleContent,
        }),
      });

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || 'Error generant el resum');
      }

      const data = await response.json();
      const generatedSummary = data.summary.trim();
      
      // Verificar que el resum generat és vàlid
      if (isValidSummary(generatedSummary)) {
        // Guardar el resum a la memòria
        summariesCache.set(articleNumber, generatedSummary);
        setSummary(generatedSummary);
        // Si s'ha generat automàticament, obrir la secció quan estigui llest
        if (!autoOpen) {
          setIsOpen(true);
        }
      } else {
        throw new Error('El resum generat no és vàlid');
      }
    } catch (err: any) {
      setError(err.message || 'Error generant el resum');
      console.error('Error:', err);
      hasAutoGenerated.current = false; // Permetre tornar a intentar
    } finally {
      setLoading(false);
    }
  }, [articleNumber, articleTitle, articleContent]);

  // Netejar el resum quan canvia l'article i carregar el guardat si existeix
  useEffect(() => {
    // Si canvia l'article, netejar l'estat local
    if (previousArticleNumber.current !== null && previousArticleNumber.current !== articleNumber) {
      setSummary(null);
      setError(null);
      setLoading(false);
      setIsOpen(false);
      hasAutoGenerated.current = false;
    }

    // Carregar el resum guardat si existeix per aquest article
    const cachedSummary = summariesCache.get(articleNumber);
    if (cachedSummary && isValidSummary(cachedSummary)) {
      setSummary(cachedSummary);
    } else if (isValidSummary(initialSummary) && initialSummary) {
      setSummary(initialSummary);
      summariesCache.set(articleNumber, initialSummary);
    }
    // NO generar automàticament - només quan l'usuari faci clic al botó

    previousArticleNumber.current = articleNumber;
  }, [articleNumber, initialSummary, generateSummary]);

  // Mostrar el botó quan no hi ha resum vàlid (no generar automàticament)
  const showGenerateButton = !summary && !loading && !error;

  return (
    <details className="article-summary" open={isOpen} onToggle={(e) => setIsOpen((e.target as HTMLDetailsElement).open)}>
      <summary className="summary-toggle">
        <div className="article-panel-header">
          <strong>RESUM</strong>
          {showGenerateButton ? (
            <button 
              onClick={(e) => {
                e.preventDefault();
                e.stopPropagation();
                generateSummary();
              }}
              className="article-panel-cta article-panel-cta--summary"
              disabled={loading}
            >
              {loading ? 'Generant...' : 'Interpretació IA'}
            </button>
          ) : (
            <span className="article-panel-placeholder" aria-hidden="true" />
          )}
          <span className="article-panel-icon summary-icon">{isOpen ? '−' : '+'}</span>
        </div>
      </summary>
      <div className="summary-content">
        {loading && (
          <div style={{ textAlign: 'center', padding: '2rem' }}>
            <div style={{ display: 'inline-block' }}>⏳ Generant resum...</div>
          </div>
        )}
        {error && (
          <div className="summary-error" style={{
            background: '#f8d7da',
            border: '1px solid #f5c6cb',
            borderRadius: '4px',
            padding: '1rem',
            color: '#721c24',
          }}>
            <strong>Error:</strong> {error}
            {error.includes('no configurada') && (
              <div style={{ marginTop: '1rem', padding: '1rem', backgroundColor: '#fff3cd', borderRadius: '4px', fontSize: '0.9rem' }}>
                <strong>⚠️ Configuració necessària:</strong>
                <p style={{ margin: '0.5rem 0 0 0' }}>
                  Per utilitzar aquesta funcionalitat, cal configurar la clau API de Groq a Vercel:
                </p>
                <ol style={{ margin: '0.5rem 0 0 1.5rem', padding: 0 }}>
                  <li>Vés a <a href="https://vercel.com/dashboard" target="_blank" rel="noopener noreferrer">Vercel Dashboard</a></li>
                  <li>Selecciona el projecte</li>
                  <li>Vés a <strong>Settings</strong> → <strong>Environment Variables</strong></li>
                  <li>Afegeix <code>GROQ_API_KEY</code> amb la teva clau API (obtinguda a <a href="https://console.groq.com" target="_blank" rel="noopener noreferrer">console.groq.com</a>)</li>
                  <li>Redeploya l'aplicació</li>
                </ol>
              </div>
            )}
            <button 
              onClick={() => generateSummary(true)}
              className="retry-button"
              style={{ marginTop: '1rem' }}
            >
              Tornar a intentar
            </button>
          </div>
        )}
        {summary && (
          <div className="summary-text">
            {summary.split('\n').map((paragraph, index) => (
              <p key={index} style={{ marginBottom: '1rem' }}>
                {paragraph}
              </p>
            ))}
          </div>
        )}
        {!summary && !loading && !error && (
          <div style={{ textAlign: 'center', padding: '2rem', color: '#666' }}>
            Fes clic a "Interpretació IA" per generar una interpretació d'aquest article.
          </div>
        )}
      </div>
    </details>
  );
};

export default SummarySection;

