import React from 'react';
import Head from 'next/head';
import Layout from '../components/Layout';
import { ArticleInterpretacioDemo } from '../components/article/ArticleInterpretacioDemo';

const ComEstaFetPage: React.FC = () => (
  <>
    <Head>
      <title>Dret Planer · Infografia de la recerca</title>
      <meta name="description" content="Infografia sobre claredat constitucional, integració jurídica i intel·ligència artificial consultiva al Principat d’Andorra." />
    </Head>
    <Layout>
      <div className="dp-infografia">
        <div className="dp-topline" />
        <nav className="dp-nav" aria-label="Navegació de la infografia">
          <a href="#inici" className="dp-brand"><span className="dp-mark">D</span><span>Dret Planer</span></a>
          <div className="dp-navlinks"><a href="#pregunta">Pregunta</a><a href="#perque">Per què?</a><a href="#claredat">Claredat</a><a href="#disseny">Disseny</a><a href="#prototip">Prototip</a><a href="#fronteres">IA</a><a href="#limits">Límits</a></div>
        </nav>

        <main>
          <section className="dp-hero" id="inici">
            <div><p className="dp-eyebrow">Claredat constitucional · Principat d’Andorra</p><h1>Comprendre el dret és entrar en el món jurídic.</h1><p className="dp-lede">Infografia-resum del manuscrit <strong>«Claredat constitucional i integració jurídica al Principat d’Andorra»</strong>: una recerca sobre hermenèutica, dret a comprendre i intel·ligència artificial consultiva.</p></div>
            <div className="dp-orbit-art" aria-label="Relació entre font, mediació i persona"><div className="dp-orbit"><span /><span /><span /><b>font<br />·<br />persona</b></div></div>
          </section>

          <section className="dp-section dp-dark" id="pregunta"><div className="dp-section-head"><div><p className="dp-eyebrow">01 · El problema</p><h2>La norma pot ser vàlida i continuar sent difícil d’entendre.</h2></div><p>La recerca parteix d’una tensió: l’accés formal a la Constitució no garanteix que la persona pugui comprendre el seu llenguatge, context, institucions i vies de protecció.</p></div><p className="dp-question">Pot una IA consultiva facilitar la comprensió de la Constitució i contribuir a la <em>integració jurídica</em> sense substituir l’autonomia ni el judici humà?</p></section>

          <section className="dp-section" id="andorra"><div className="dp-section-head"><div><p className="dp-eyebrow">02 · El cas andorrà</p><h2>Una societat plural necessita una entrada comprensible al dret compartit.</h2></div><p>La pregunta no és només qui pot votar. És qui viu sota normes, utilitza institucions, assumeix obligacions i necessita saber com protegir els seus drets.</p></div><div className="dp-stat-grid"><article className="dp-stat"><div className="dp-number">≈55<sup>%</sup></div><small>resident amb nacionalitat estrangera</small><p>Xifra de treball del manuscrit, pendent d’actualització estadística abans de publicar-la com a dada vigent.</p></article><article className="dp-stat"><h3>Subjecte de drets</h3><p>La persona resident és destinatària de l’ordenament i pot trobar-se davant de normes, procediments i institucions.</p></article><article className="dp-stat"><h3>No és assimilació</h3><p>La integració jurídica ofereix eines per comprendre i defensar la pròpia posició jurídica.</p></article></div></section>

          <section className="dp-section dp-dark" id="perque"><div className="dp-section-head"><div><p className="dp-eyebrow">03 · Per què?</p><h2>Perquè el dret també apareix en les decisions petites del dia a dia.</h2></div><p>Dret Planer pot servir com una primera orientació perquè la persona entengui què està llegint, quina pregunta ha de formular i quin és el pas següent.</p></div><div className="dp-cards dp-cards-3">{[['Entendre','Quan reps una notificació','Identificar què t’estan comunicant, quina norma hi apareix i què cal aclarir abans d’actuar.'],['Preparar','Abans d’anar a una institució','Arribar amb una pregunta més concreta, saber quina administració pot ser competent i localitzar la font oficial.'],['Comparar','Quan trobes una explicació en línia','Contrastar una resposta senzilla amb el text jurídic original i detectar si falta context.'],['Decidir','Quan no saps si necessites ajuda','Obtenir una orientació inicial i reconèixer quan cal acudir a un professional.'],['Aprendre','Quan vols entendre el sistema','Relacionar drets, obligacions, institucions i procediments.'],['Autonomia','No rebre només una resposta','Aprendre a preguntar millor i seguir les fonts sense delegar el propi judici.']].map(([tag, title, text]) => <article className="dp-card" key={title}><span>{tag}</span><h3>{title}</h3><p>{text}</p></article>)}</div><p className="dp-disclaimer">Serveix per orientar i preparar-se; no substitueix l’assessorament jurídic, la decisió d’una institució ni la revisió del cas concret.</p></section>

          <section className="dp-section dp-soft" id="marc"><div className="dp-section-head"><div><p className="dp-eyebrow">04 · Tres dimensions teòriques</p><h2>La Constitució és realitat, cultura i pla jurídic compartit.</h2></div><p>Heller, Häberle i Shapiro permeten passar de la teoria a criteris de disseny per a una mediació comprensible.</p></div><div className="dp-cards dp-cards-3">{[['01 / Heller','Realitat històrica i institucional','La norma pren sentit dins d’una trajectòria, unes institucions, unes pràctiques i una experiència col·lectiva.'],['02 / Häberle','Cultura oberta d’intèrprets','La societat també necessita eines per preguntar, interpretar i situar-se.'],['03 / Shapiro','Planificació social','El dret coordina una comunitat mitjançant un pla jurídic compartit que ha de poder ser conegut i comprès.']].map(([tag, title, text]) => <article className="dp-card" key={title}><span>{tag}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

          <section className="dp-section" id="claredat"><div className="dp-section-head"><div><p className="dp-eyebrow">05 · Dret a comprendre</p><h2>La claredat constitucional té tres capes.</h2></div><p>Fer planer el dret no és només simplificar frases: és conservar la font, fer intel·ligible l’estructura i explicar el context.</p></div><div className="dp-cards dp-cards-3">{[['Accés','Cognoscibilitat','Arribar a la norma, identificar-la i consultar-ne la font original.'],['Llenguatge','Intel·ligibilitat','Entendre el vocabulari, la sintaxi i l’estructura del text jurídic.'],['Context','Contextualització','Relacionar la norma amb institucions, procediments, drets i situacions.']].map(([tag, title, text]) => <article className="dp-card" key={title}><span>{tag}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="dp-document"><div><span>Font jurídica original</span><h3>La norma conserva la seva autoritat.</h3><p>Text, versió, jerarquia i referència verificable.</p></div><div><span>Explicació plana</span><h3>La mediació redueix barreres cognitives.</h3><p>Traducció, simplificació, explicació i context, sense dissoldre la font.</p></div></div></section>

          <section className="dp-section" id="disseny"><div className="dp-section-head"><div><p className="dp-eyebrow">06 · De la teoria al disseny</p><h2>L’hermenèutica es converteix en una mediació visible.</h2></div><p>El prototip no és una caixa negra: cada part de la seva arquitectura respon a una exigència de comprensió i integració jurídica.</p></div><div className="dp-cards dp-cards-2">{[['Comprensió','De la norma al significat','El sistema parteix d’un corpus controlat i ajuda a entendre què diu la font i en quin context jurídic opera.'],['Context','La norma dins del sistema','Constitució, jurisprudència, doctrina i història no es barregen: es relacionen i es distingeixen.'],['Integració','Participar sense quedar fora','La mediació ajuda a comprendre i formular preguntes; no substitueix el judici ni la decisió humana.'],['Responsabilitat','Fer visible d’on surt','La resposta conserva la relació amb els documents recuperats, la versió del corpus i els seus límits.']].map(([tag, title, text]) => <article className="dp-card" key={title}><span>{tag}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

          <section className="dp-section dp-dark" id="prototip"><div className="dp-section-head"><div><p className="dp-eyebrow">07 · Del principi al prototip</p><h2>Una rampa cognitiva, no un oracle.</h2></div><p>El sistema recupera, ordena i explica. La persona conserva la capacitat de preguntar, contrastar i decidir.</p></div><div className="dp-flow">{[['Pregunta','La persona formula una qüestió en llenguatge natural.'],['Recuperació','El sistema cerca en fonts jurídiques delimitades.'],['Context','Distingeix norma, doctrina, jurisprudència i context.'],['Explicació','Construeix una resposta plana i traçable.'],['Abstenció','Mostra incertesa i deriva quan no pot respondre amb seguretat.']].map(([title, text]) => <div key={title}><strong>{title}</strong><small>{text}</small></div>)}</div></section>

          <div id="interpretacio-article-2"><ArticleInterpretacioDemo /></div>

          <section className="dp-section dp-dark" id="fronteres"><div className="dp-section-head"><div><p className="dp-eyebrow">08 · IA generativa / noves fronteres</p><h2>La IA també participa en la construcció de la recerca.</h2></div><p>La IA no només és objecte d’estudi o motor del prototip: també intervé en la programació i en la transformació de les idees en estructures digitals.</p></div><div className="dp-cards dp-cards-3">{[['01 / Instrument','La IA produeix','Genera codi, estructures, síntesis i variants que acceleren el prototip.'],['02 / Recerca','El prompt orienta','Les instruccions incorporen criteris jurídics i converteixen la teoria en comportaments examinables.'],['03 / Responsabilitat','La persona decideix','La selecció de fonts, l’avaluació i les conclusions continuen sota control humà.']].map(([tag, title, text]) => <article className="dp-card" key={title}><span>{tag}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="dp-long-copy"><p>Aquesta participació no elimina l’autoria investigadora. La desplaça cap a una activitat de <strong>definició, selecció, supervisió i verificació</strong>.</p><p>Els prompts no són simples ordres: són <strong>instruments d’investigació</strong>. Tradueixen una hipòtesi jurídica en una instrucció operativa.</p><p>La nova frontera no consisteix a afirmar que la IA pensa jurídicament, sinó a explorar què pot fer la recerca jurídica mantenint la responsabilitat crítica en la persona investigadora.</p></div></section>

          <section className="dp-section dp-soft" id="limits"><div className="dp-section-head"><div><p className="dp-eyebrow">09 · Condicions de responsabilitat</p><h2>Integrar no vol dir substituir.</h2></div><p>La tecnologia només és defensable si deixa visibles les seves fonts, els seus límits i la responsabilitat humana.</p></div><ul className="dp-limits"><li>No és autoritat interpretativa.</li><li>No substitueix juristes, tribunals ni institucions.</li><li>No converteix doctrina en dret positiu.</li><li>No prova per si sola que hi hagi comprensió.</li></ul><div className="dp-cards dp-cards-3 dp-evaluation">{[['01 / Tècnica','Recuperació','La font recuperada és pertinent, completa i identificable?'],['02 / Jurídica','Fidelitat','La resposta respecta el text, la jerarquia i el context?'],['03 / Empírica','Comprensió','La persona entén millor el dret? Això exigeix proves específiques.']].map(([tag, title, text]) => <article className="dp-card" key={title}><span>{tag}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

          <section className="dp-closing"><p className="dp-eyebrow">Idea central</p><h2>La tecnologia és la mediació. La integració jurídica és la finalitat.</h2><p>El projecte explora si una IA consultiva pot fer més cognoscible, intel·ligible i contextual la Constitució andorrana, preservant l’autonomia de la persona i la responsabilitat humana.</p></section>
        </main>

        <style jsx>{`
          .dp-infografia { --ink:#172622; --muted:#66756e; --paper:#f5f1e9; --paper2:#e7eee8; --line:#d4ddd4; --forest:#143d33; --green:#2d7a5d; --mint:#bcdccb; --orange:#db794d; --yellow:#efc861; --white:#fffdf8; color:var(--ink); background:var(--paper); font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif; line-height:1.5; margin:0 -1rem; }
          .dp-topline { height:8px; background:linear-gradient(90deg,var(--orange) 0 25%,var(--yellow) 25% 50%,var(--green) 50% 75%,var(--forest) 75%); }
          .dp-nav { position:sticky; top:0; z-index:20; display:flex; justify-content:space-between; align-items:center; gap:18px; padding:15px clamp(22px,5vw,70px); background:rgba(245,241,233,.94); border-bottom:1px solid var(--line); backdrop-filter:blur(12px); }
          .dp-brand { display:flex; align-items:center; gap:10px; color:var(--forest); font-size:.8rem; font-weight:800; letter-spacing:.1em; text-transform:uppercase; }
          .dp-mark { display:grid; place-items:center; width:30px; height:30px; border-radius:50%; color:var(--white); background:var(--forest); font-family:Georgia,serif; font-size:1.1rem; box-shadow:8px -5px 0 var(--yellow); }
          .dp-navlinks { display:flex; gap:15px; color:var(--muted); font-size:.75rem; }
          .dp-navlinks a:hover { color:var(--forest); }
          .dp-hero,.dp-section { padding:86px clamp(22px,8vw,110px); }
          .dp-hero { display:grid; grid-template-columns:1.05fr .95fr; gap:7vw; align-items:center; background:var(--white); }
          .dp-eyebrow { margin:0 0 15px; color:var(--orange); font-size:.7rem; font-weight:850; letter-spacing:.16em; text-transform:uppercase; }
          .dp-dark .dp-eyebrow { color:var(--yellow); }
          .dp-hero h1,.dp-section h2,.dp-closing h2 { margin:0; font:400 clamp(2.7rem,5vw,5.8rem)/.94 Georgia,'Times New Roman',serif; letter-spacing:-.055em; }
          .dp-lede { max-width:650px; margin:28px 0 0; color:#4f5e57; font-size:1.12rem; }
          .dp-orbit-art { display:grid; place-items:center; min-height:410px; }
          .dp-orbit { position:relative; width:min(34vw,390px); aspect-ratio:1; border:1px solid #9cc0aa; border-radius:50%; background:radial-gradient(circle at 50% 44%,var(--mint) 0 28%,transparent 28.5%),radial-gradient(circle,transparent 0 48%,#dbe9df 48.5% 49%,transparent 49.5%); }
          .dp-orbit:before,.dp-orbit:after { content:''; position:absolute; inset:13%; border:1px dashed #80ae96; border-radius:50%; }.dp-orbit:after { inset:29%; border-style:solid; border-color:var(--orange); }
          .dp-orbit span { position:absolute; width:15px; height:15px; border-radius:50%; background:var(--orange); top:-8px; left:calc(50% - 8px); }.dp-orbit span:nth-child(2){top:auto;left:auto;right:2%;bottom:11%;background:var(--yellow)}.dp-orbit span:nth-child(3){top:25%;left:4%;background:var(--green)}
          .dp-orbit b { position:absolute; inset:0; display:grid; place-content:center; text-align:center; color:var(--forest); font:400 1.45rem/1.05 Georgia,serif; }
          .dp-dark { color:var(--white); background:var(--forest); }.dp-soft { background:var(--paper2); }.dp-section-head { display:grid; grid-template-columns:minmax(0,1.15fr) minmax(240px,.85fr); gap:7vw; align-items:end; margin-bottom:45px; }.dp-section-head > p { margin:0; color:var(--muted); font-size:1rem; }.dp-dark .dp-section-head > p,.dp-dark .dp-disclaimer,.dp-dark .dp-long-copy { color:#c2d5ca; }
          .dp-question { margin:0; padding:28px 0 5px; border-top:1px solid currentColor; border-bottom:1px solid currentColor; font:400 clamp(1.7rem,3.2vw,3.5rem)/1.04 Georgia,serif; }.dp-question em{color:var(--orange);font-style:normal}
          .dp-stat-grid,.dp-cards { display:grid; gap:14px; }.dp-stat-grid,.dp-cards-3 { grid-template-columns:repeat(3,1fr); }.dp-cards-2 { grid-template-columns:repeat(2,1fr); }.dp-stat,.dp-card { padding:27px; border:1px solid var(--line); background:rgba(255,253,248,.78); }.dp-dark .dp-card { background:rgba(8,40,32,.55); border-color:rgba(255,255,255,.24); }.dp-card span { color:var(--orange); font-size:.7rem; font-weight:850; letter-spacing:.12em; text-transform:uppercase; }.dp-dark .dp-card span{color:var(--yellow)}.dp-stat h3,.dp-card h3{margin:17px 0 11px;font:400 1.45rem/1.02 Georgia,serif;letter-spacing:-.03em}.dp-card p,.dp-stat p{margin:0;color:#56655e}.dp-dark .dp-card h3,.dp-dark .dp-card p{color:var(--white)}.dp-dark .dp-card p{color:#c2d5ca}.dp-number{margin-bottom:20px;color:var(--orange);font:400 clamp(4.8rem,9vw,9rem)/.7 Georgia,serif;letter-spacing:-.1em}.dp-stat small{color:var(--muted);font-size:.7rem;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.dp-stat > p{margin-top:18px;font-size:.78rem}.dp-disclaimer{margin:22px 0 0;font-size:.78rem}.dp-document{display:grid;grid-template-columns:1fr 1fr;margin-top:42px;border:1px solid var(--forest)}.dp-document > div{min-height:220px;padding:30px}.dp-document > div:first-child{color:var(--white);background:var(--forest)}.dp-document > div:last-child{background:var(--yellow)}.dp-document span{font-size:.7rem;font-weight:850;letter-spacing:.12em;text-transform:uppercase}.dp-document h3{margin:16px 0 10px;font:400 1.8rem/1.02 Georgia,serif}.dp-document p{margin:0}.dp-flow{display:grid;grid-template-columns:repeat(5,1fr);border-top:1px solid rgba(255,255,255,.3);border-bottom:1px solid rgba(255,255,255,.3)}.dp-flow > div{min-height:190px;padding:25px 18px;border-right:1px solid rgba(255,255,255,.24)}.dp-flow > div:last-child{border-right:0}.dp-flow strong{display:block;margin-bottom:68px;color:var(--yellow);font:400 1.45rem/1 Georgia,serif}.dp-flow small{color:#c2d5ca}.dp-long-copy{max-width:900px;margin-top:40px;font-size:1.05rem}.dp-long-copy strong{color:var(--yellow)}.dp-limits{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:0;padding:0;list-style:none}.dp-limits li{min-height:130px;padding:20px;background:var(--white);border-top:4px solid var(--orange);font-weight:750}.dp-evaluation{margin-top:45px}.dp-closing{padding:95px clamp(22px,8vw,110px);color:var(--white);text-align:center;background:var(--orange)}.dp-closing .dp-eyebrow{color:var(--white)}.dp-closing h2{max-width:850px;margin:0 auto}.dp-closing > p:last-child{max-width:700px;margin:25px auto 0;color:#fff2e9;font-size:1.08rem}
          @media(max-width:850px){.dp-navlinks{display:none}.dp-hero,.dp-section{padding:65px 7vw}.dp-hero{grid-template-columns:1fr}.dp-orbit-art{min-height:300px}.dp-orbit{width:min(70vw,350px)}.dp-section-head{display:block}.dp-section-head > p{margin-top:22px}.dp-stat-grid,.dp-cards-3,.dp-cards-2,.dp-limits{grid-template-columns:1fr}.dp-document{grid-template-columns:1fr}.dp-flow{grid-template-columns:1fr}.dp-flow > div{min-height:auto;border-right:0;border-bottom:1px solid rgba(255,255,255,.24)}.dp-flow strong{margin-bottom:12px}.dp-limits{gap:10px}}
        `}</style>
      </div>
    </Layout>
  </>
);

export default ComEstaFetPage;
